# Generated by Django 4.1.7 on 2023-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RecordType", models.CharField(max_length=255)),
                ("Type", models.CharField(max_length=255)),
                ("TypeCode", models.CharField(max_length=255)),
                ("Name", models.CharField(max_length=255)),
                ("Tag", models.CharField(max_length=255)),
                ("MessageStream", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("From", models.EmailField(max_length=254)),
                ("Email", models.EmailField(max_length=254)),
                ("BouncedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
