# Generated by Django 4.1.7 on 2023-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smessanger", "0002_alter_slackmessage_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackmessage",
            name="Email",
            field=models.EmailField(max_length=254),
        ),
    ]
